# /*

E-Commerce Analytics Queries
Project: Ecommerce Data Platform
Purpose: Business insights from the Data Warehouse
==================================================

*/

/* ========================================

1. Total Revenue
   Business Question:
   What is the total revenue generated by the store?
   ======================================== */

SELECT
SUM(revenue) AS total_revenue
FROM fact_sales;

/* ========================================
2. Revenue by Country
Business Question:
Which countries generate the most revenue?
======================================== */

SELECT
c.country_name,
SUM(f.revenue) AS revenue
FROM fact_sales f
JOIN dim_country c
ON f.country_id = c.country_id
GROUP BY c.country_name
ORDER BY revenue DESC;

/* ========================================
3. Top 10 Products by Units Sold
Business Question:
Which products are the most popular?
======================================== */

SELECT
p.product_name,
SUM(f.quantity) AS total_units_sold
FROM fact_sales f
JOIN dim_products p
ON f.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_units_sold DESC
LIMIT 10;

/* ========================================
4. Top 10 Products by Revenue
Business Question:
Which products generate the most revenue?
======================================== */

SELECT
p.product_name,
SUM(f.revenue) AS revenue
FROM fact_sales f
JOIN dim_products p
ON f.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 10;

/* ========================================
5. Monthly Revenue Trend
Business Question:
How do sales evolve over time?
======================================== */

SELECT
d.year,
d.month,
SUM(f.revenue) AS monthly_revenue
FROM fact_sales f
JOIN dim_date d
ON f.date_id = d.date_id
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

/* ========================================
6. Top Customers by Spending
Business Question:
Which customers spend the most?
======================================== */

SELECT
cu.customer_id,
SUM(f.revenue) AS total_spent
FROM fact_sales f
JOIN dim_customers cu
ON f.customer_id = cu.customer_id
GROUP BY cu.customer_id
ORDER BY total_spent DESC
LIMIT 10;

/* ========================================
7. Average Order Value
Business Question:
How much does a customer spend on average per order?
======================================== */

SELECT
AVG(order_total) AS average_order_value
FROM (
SELECT
invoice_no,
SUM(revenue) AS order_total
FROM fact_sales
GROUP BY invoice_no
) orders;

/* ========================================
8. Number of Orders by Country
Business Question:
Which countries generate the most orders?
======================================== */

SELECT
c.country_name,
COUNT(DISTINCT f.invoice_no) AS total_orders
FROM fact_sales f
JOIN dim_country c
ON f.country_id = c.country_id
GROUP BY c.country_name
ORDER BY total_orders DESC;

/* ========================================
9. Repeat vs One-Time Customers
Business Question:
What percentage of customers are repeat buyers?
======================================== */

SELECT
    CASE
        WHEN order_count = 1 THEN 'One-Time Customer'
        ELSE 'Repeat Customer'
    END AS customer_type,
    COUNT(*) AS customer_count
FROM (
    SELECT
        customer_id,
        COUNT(DISTINCT invoice_no) AS order_count
    FROM fact_sales
    GROUP BY customer_id
) customer_orders
GROUP BY customer_type;

/* ========================================
10. Customer Lifetime Value
Business Question:
How much revenue does each customer generate?
======================================== */

SELECT
    customer_id,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(revenue) AS lifetime_value
FROM fact_sales
GROUP BY customer_id
ORDER BY lifetime_value DESC
LIMIT 10;